### ISSUE TITLE
Trouble with Authentication Headers

### ISSUE THREAD

**Issue by vallieres** [dave/blast#3]
Hello,

I'm trying to use Blast with a simple GET request that needs a Bearer token and I keep getting either errors (401) or JSON parsing errors.

```
rate: 1
workers: 1
worker-type: "http"
log: "out.log"
headers: "[\"Authorization: Bearer ey--TQ\"]"
payload-template:
  method: "GET"
  path: "/v1/object/abcdefg1234567"
worker-template:
  print: true
  base: "https://sub.domain.com"
```

I tried with dummy worker-type too, and I was not able to make it work. Using the same information I can do a cURL command successfully, so I know the URL + auth should work.

Any ideas how I can achieve this?
